/**
 * RAPTOR Database Package
 *
 * Exports database types and utilities.
 */

// Database types are generated by Supabase CLI
// Run: npm run generate (requires SUPABASE_PROJECT_ID)

export interface DatabaseConfig {
  supabaseUrl: string;
  supabaseKey: string;
}
